config/routes.rb
Rails.application.routes.draw do
  resources :user_temp_admins
  get 'mercadopago/index'
  get 'mercadopago/show'
  get 'mercadopago/new'
  get 'user_temp_sups/index'
  get 'user_temp_sups/show'
  get 'user_temp_sups/new',as:"new_user_temp_sup"
  resources :user_temp_sups
  #Rutas del admin
  resources :cars
  get "cars/pausar/:id", to: "cars#changeEnable",as:"cars_lista_id"
  patch "cars/pausar/:id", to: "cars#changeEnable",as:"cars_pausar"
  get "cars/activar/:id", to: "cars#changeEnable",as:"cars_lista_activar_id"
  patch "cars/activar/:id", to: "cars#changeEnable",as:"cars_activar"
  get "cars/delete/:id", to: "cars#destroy"
  delete "cars/delete/:id", to: "cars#destroy", as:"cars_delete"
  get "cars/deleteCar/:id", to: "cars#deleteCar"
  delete "cars/deleteCar/:id", to: "cars#deleteCar", as:"cars_deletecar"
  #Rutas del admin
  get "users/admin", to: "users#userAdmin", as: "user_admin"
  get "users/admin/newSup", to: "users#newSup", as: "user_admin_agregarSupervisor"
  post "users/admin", to: "users#create"
  get "users/admin/listaSupervisor", to: "users#userAdmin_listaSupervisor", as: "user_admin_lista"
  get "users/admin/listaAdministradores", to: "users#userAdmin_listAdmin", as: "user_admin_listaAdmin"
  get '/user/:id', to: 'users#show', as: 'user'
  get 'users/admin/listaSupervisor/:id/edit_employees', to: 'users#userAdmin_editEmployees', as: 'user_admin_editEmployees'
  patch 'user/:id', to: 'users#update_Employees'
  get "users/admin/listaSupervisor/:id", to: "users#deleteSup", as: "user_admin_lista_id"
  delete 'users/admin/listaSupervisor/:id', to: 'users#deleteSup', as: 'superv_delete'
  #Rutas del usuario
  get "users/usuario", to: "users#userUsuario", as: "user_usuario"
  get "users/usuario/actualizarLicencia", to: "users#actualizarLicencia", as: "user_usuario_actualizarLicencia"

  
  #Rutas del supervisor
  get "users/supervisor", to: "users#userSupervisor", as: "user_supervisor"
  resources :users, only: [:index]
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "users#home"


  get 'users/supervisor/listaLicencias', to: 'users#listaLicencias', as: 'listar_licencias'

  get 'users/supervisor/confirm/:id', to: 'users#validarLic', as: 'validar_licencia_id'
  patch 'users/supervisor/confirm/:id', to: 'users#validarLic', as: 'validar_licencia'

  get 'users/supervisor/confirm/rechazar/:id', to: 'users#rechazarLic', as: 'rechazar_licencia_id'
  patch 'users/supervisor/confirm/rechazar/:id', to: 'users#rechazarLic', as: 'rechazar_licencia'


  get 'users/usuario/:id/elegirsaldo', to: 'users#elegirSaldo', as: 'elegir_saldo'


  get 'mercadopago/success', to: 'mercadopago#success'
  get 'mercadopago/pending', to: 'mercadopago#pending'
  get 'mercadopago/failure', to: 'mercadopago#failure'

end

app/models/user_temp_admin.rb
class UserTempAdmin < ApplicationRecord
end

app/controllers/user_temp_admins_controller.rb
class UserTempAdminsController < ApplicationController
  before_action :set_user_temp_admin, only: %i[ show edit update destroy ]

  # GET /user_temp_admins or /user_temp_admins.json
  def index
    @user_temp_admins = UserTempAdmin.all
  end

  # GET /user_temp_admins/1 or /user_temp_admins/1.json
  def show
  end

  # GET /user_temp_admins/new
  def new
    @user_temp_admin = UserTempAdmin.new
  end

  # GET /user_temp_admins/1/edit
  def edit
  end

  # POST /user_temp_admins or /user_temp_admins.json
  def create
    @user_temp_admin = UserTempAdmin.new(user_temp_admin_params)
    if @user_temp_admin.save
      @user_temp_admin=User.create(name: @user_temp_admin.name, last_name: @user_temp_admin.last_name, dni_nro:  @user_temp_admin.dni_nro, email:  @user_temp_admin.email, password:  @user_temp_admin.password, role: "administrador", password_confirmation: @user_temp_admin.password_confirmation)
    end
    respond_to do |format|
      if @user_temp_admin.save
        format.html { redirect_to user_admin_listaAdmin_path, notice: "Se ha creado el administrador con exito" }
        format.json { render :show, status: :created, location: @user_temp_admin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_temp_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_temp_admins/1 or /user_temp_admins/1.json
  def update
    respond_to do |format|
      if @user_temp_admin.update(user_temp_admin_params)
        format.html { redirect_to user_temp_admin_url(@user_temp_admin), notice: "User temp admin was successfully updated." }
        format.json { render :show, status: :ok, location: @user_temp_admin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_temp_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_temp_admins/1 or /user_temp_admins/1.json
  def destroy
    @user_temp_admin.destroy

    respond_to do |format|
      format.html { redirect_to user_temp_admins_url, notice: "User temp admin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_temp_admin
      @user_temp_admin = UserTempAdmin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_temp_admin_params
      params.require(:user_temp_admin).permit(:name, :last_name, :dni_nro, :email, :password, :password_confirmation)
    end
end

app/helpers/user_temp_admins_helper.rb
module UserTempAdminsHelper
end

app/views/user_temp_admins/_form.html.erb
<div class="text-center has-text-weight-bold ">
<section class="hero is-warning is-fullheight is-small">
  <div class="hero-body ">
    <div class="container">
      <div class="columns is-centered ">
        <div class="column is-5-tablet is-4-desktop is-4-widescreen box">
<%= form_with(model: user_temp_admin) do |form| %>
  <% if user_temp_admin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_temp_admin.errors.count, "errores") %></h2>

      <ul>
        <% user_temp_admin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name,"Nombre",style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :last_name,"Apellido",style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :dni_nro,"DNI", style: "display: block" %>
    <%= form.text_field :dni_nro %>
  </div>

  <div>
    <%= form.label :email, "Email", style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password,"Contraseña", style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation,"Confirmar contraseña",style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>
  <br>
  <div>
    <%= form.submit "Crear", class:"button is-warning is-outlined is-light",data: { turbo_confirm:'Estas seguro de que desea agregar un administrador?' }%>
  </div>
  <br>
  <div class = "text-center ">
          <%= link_to "Volver",  user_admin_listaAdmin_path, class: "button is-warning is-outlined is-light" %>
  </div>
<% end %>
</div>
</div>
</div>
</div>
</section>
</div>

app/views/user_temp_admins/_user_temp_admin.html.erb
<div id="<%= dom_id user_temp_admin %>">
  <p>
    <strong>Name:</strong>
    <%= user_temp_admin.name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user_temp_admin.last_name %>
  </p>

  <p>
    <strong>Dni nro:</strong>
    <%= user_temp_admin.dni_nro %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user_temp_admin.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user_temp_admin.password %>
  </p>

  <p>
    <strong>Password confirmation:</strong>
    <%= user_temp_admin.password_confirmation %>
  </p>

</div>

app/views/user_temp_admins/edit.html.erb
<h1>Editing user temp admin</h1>

<%= render "form", user_temp_admin: @user_temp_admin %>

<br>

<div>
  <%= link_to "Show this user temp admin", @user_temp_admin %> |
  <%= link_to "Back to user temp admins", user_temp_admins_path %>
</div>

app/views/user_temp_admins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User temp admins</h1>

<div id="user_temp_admins">
  <% @user_temp_admins.each do |user_temp_admin| %>
    <%= render user_temp_admin %>
    <p>
      <%= link_to "Show this user temp admin", user_temp_admin %>
    </p>
  <% end %>
</div>

<%= link_to "New user temp admin", new_user_temp_admin_path %>

app/views/user_temp_admins/new.html.erb
<nav class="navbar navbar-light is-warning">
  <a class="navbar-brand" href="">
    <%= image_submit_tag('ACA.png')%>
    <div class= "text-right">
         <%= link_to "Cerrar sesión", destroy_user_session_path, 'data-turbo.method': :delete, class:"button is-warning is-outlined is-light"%>
    </div>
  </a>
</nav>

<section class="hero is-warning is-small">
  <div class="hero-body ">
      <h3 class="text-center">Agregar administrador</h3>
        <%= render "form", user_temp_admin: @user_temp_admin %>
  </div>
</section>

app/views/user_temp_admins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_temp_admin %>

<div>
  <%= link_to "Edit this user temp admin", edit_user_temp_admin_path(@user_temp_admin) %> |
  <%= link_to "Back to user temp admins", user_temp_admins_path %>

  <%= button_to "Destroy this user temp admin", @user_temp_admin, method: :delete %>
</div>