config/routes.rb
Rails.application.routes.draw do
  resources :user_temp_admins
  get 'mercadopago/index'
  get 'mercadopago/show'
  get 'mercadopago/new'
  get 'user_temp_sups/index'
  get 'user_temp_sups/show'
  get 'user_temp_sups/new',as:"new_user_temp_sup"
  resources :user_temp_sups
  #Rutas del admin
  resources :cars
  get "cars/pausar/:id", to: "cars#changeEnable",as:"cars_lista_id"
  patch "cars/pausar/:id", to: "cars#changeEnable",as:"cars_pausar"
  get "cars/activar/:id", to: "cars#changeEnable",as:"cars_lista_activar_id"
  patch "cars/activar/:id", to: "cars#changeEnable",as:"cars_activar"
  get "cars/delete/:id", to: "cars#destroy"
  delete "cars/delete/:id", to: "cars#destroy", as:"cars_delete"
  get "cars/deleteCar/:id", to: "cars#deleteCar"
  delete "cars/deleteCar/:id", to: "cars#deleteCar", as:"cars_deletecar"
  #Rutas del admin
  get "users/admin", to: "users#userAdmin", as: "user_admin"
  get "users/admin/newSup", to: "users#newSup", as: "user_admin_agregarSupervisor"
  post "users/admin", to: "users#create"
  get "users/admin/listaSupervisor", to: "users#userAdmin_listaSupervisor", as: "user_admin_lista"
  get "users/admin/listaAdministradores", to: "users#userAdmin_listAdmin", as: "user_admin_listaAdmin"
  get '/user/:id', to: 'users#show', as: 'user'
  get 'users/admin/listaSupervisor/:id/edit_employees', to: 'users#userAdmin_editEmployees', as: 'user_admin_editEmployees'
  patch 'user/:id', to: 'users#update_Employees'
  get "users/admin/listaSupervisor/:id", to: "users#deleteSup", as: "user_admin_lista_id"
  delete 'users/admin/listaSupervisor/:id', to: 'users#deleteSup', as: 'superv_delete'
  #Rutas del usuario
  get "users/usuario", to: "users#userUsuario", as: "user_usuario"
  get "users/usuario/actualizarLicencia", to: "users#actualizarLicencia", as: "user_usuario_actualizarLicencia"

  
  #Rutas del supervisor
  get "users/supervisor", to: "users#userSupervisor", as: "user_supervisor"
  resources :users, only: [:index]
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "users#home"


  get 'users/supervisor/listaLicencias', to: 'users#listaLicencias', as: 'listar_licencias'

  get 'users/supervisor/confirm/:id', to: 'users#validarLic', as: 'validar_licencia_id'
  patch 'users/supervisor/confirm/:id', to: 'users#validarLic', as: 'validar_licencia'

  get 'users/supervisor/confirm/rechazar/:id', to: 'users#rechazarLic', as: 'rechazar_licencia_id'
  patch 'users/supervisor/confirm/rechazar/:id', to: 'users#rechazarLic', as: 'rechazar_licencia'


  get 'users/usuario/:id/elegirsaldo', to: 'users#elegirSaldo', as: 'elegir_saldo'


  get 'mercadopago/success', to: 'mercadopago#success'
  get 'mercadopago/pending', to: 'mercadopago#pending'
  get 'mercadopago/failure', to: 'mercadopago#failure'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :dni_nro, uniqueness:  { message: 'ya existe en el sistema' }, presence: { message: 'en blanco' }
  validates :name, presence:  { message: 'en blanco' }
  validates :last_name, presence:  { message: 'en blanco' }
  validates :license, presence: { message: 'en blanco' }, if: :usuario? 
  #validates :dni, presence:  { message: 'en blanco' },if: :usuario? 
  validates :birthdate, presence:  { message: 'en blanco' },if: :usuario? 
  validates :phone, uniqueness: { message: 'ya existe en el sistema' }, presence:  { message: 'en blanco' },if: :usuario? 
  validate :acceptable_image,if: :usuario? 
  validate :acceptable_image2,if: :usuario? 
  validates :vencimiento_licencia, presence:  { message: 'en blanco' },if: :usuario?
  #validates :email, uniqueness: { message: 'ya existe en el sistema' }, presence:  { message: 'en blanco' }
  #validates :password, uniqueness: { message: 'ya existe en el sistema' }, presence:  { message: 'en blanco' }
  has_one_attached :license
  has_one_attached :dni
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:usuario, :supervisor, :administrador]
  
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role  
    self.role ||= :usuario
  end

  def usuario
    self.role == "usuario"
  end
  #validacion para que las fotos que se suban sean JPEG O PNG
  def acceptable_image
    acceptable_types = ["image/jpeg", "image/png", "image/jpg"]
    unless acceptable_types.include?(license.content_type)
      errors.add(:license, "Foto debe ser una imagen JPEG, JPG o PNG")
    end
  end
  def acceptable_image2
    acceptable_types = ["image/jpeg", "image/png", "image/jpg"]
    unless acceptable_types.include?(dni.content_type)
      errors.add(:dni, "Foto debe ser una imagen JPEG, JPG o PNG")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  add_flash_types :danger,:warning, :notice

    def index
      @users = User.all
    end
      
    def new
      @user = User.new
    end

    def show
      @userU=User.find(params[:id])
    end

    def home
       if current_user 
          if current_user.role == "administrador"
            redirect_to user_admin_path
          end
          if current_user.role == "usuario"
            redirect_to user_usuario_path
          end
          if current_user.role == "supervisor"
            redirect_to user_supervisor_path
          end
       end
    end

    def actualizarLicencia
      if current_user
        if current_user.role = "usuario"
          @userU=User.find(current_user.id)
          @userU.licencia_rechazada=false #si cambio la fecha de vencimiento vuelve a la lista de verificar licencia
          @userU.save
        end
      end
    end
    
    def userAdmin_listAdmin
      @admin= User.where(role: "administrador")
    end

    def userAdmin_listaSupervisor
      @supervisores= User.where(role: "supervisor")
    end

    def userAdmin_editEmployees
      @supervisor = User.find(params[:id])
    end

    def update_Employees
      @supervisor = User.find(params[:id])
      if @supervisor.update(supervisor_params)
        if(@supervisor.role=="usuario")
          redirect_to mercadopago_index_path
        else
          redirect_to user_admin_lista_path , notice: "Se ha editado el supervisor con exito"
        end
      else
        redirect_to user_admin_editEmployees_path, danger: "Ha ocurrido un error al agregar supervisor, revise que los campos no esten vacios o repetidos"
      end
    end

    def deleteSup
      @supervisor= User.find(params[:id])
      if @supervisor.reclamo
        redirect_to user_admin_lista_path, danger: "No se puede eliminar supervisor porque tiene un reclamo activo"
      else
       @supervisor.destroy
       redirect_to user_admin_lista_path, notice: "El supervisor se ha eliminado correctamente"
      end
    end

    def userUsuario
      @usuario=current_user
    end

    def userSupervisor
      @supervisor=current_user
    end

    def userAdmin
      @admin=current_user
    end

    def listaLicencias
      @usuarios= User.where(role: "usuario", hayLicencia: false, licencia_rechazada: false)
    end
    
    def validarLic
      @usuario= User.find(params[:id])
      @usuario.hayLicencia=true
      if @usuario.save
        redirect_to listar_licencias_path,notice: "La licencia se ha validado correctamente"
      else
        redirect_to listar_licencias_path, danger: "Hubo un error al validar la licenca, reintente por favor"
      end   
    end
     
    def rechazarLic
      @usuario= User.find(params[:id])
      @usuario.licencia_rechazada=true
      if @usuario.save
        redirect_to listar_licencias_path,notice: "La licencia se ha rechazado correctamente"
      else
        redirect_to listar_licencias_path, danger: "Hubo un error al rechazar la licenca, reintente por favor"
      end
    end

    def elegirSaldo
      @us=User.find(current_user.id)
    end
    
  

    private
    def supervisor_params
      params.require(:user).permit(:email, :name, :last_name, :dni_nro,:license,:vencimiento_licencia, :horas, :saldo)
    end
    def user_params
      params.require(:user).permit(:horas,:saldo)
    end

    

end 

app/views/users/actualizarLicencia.html.erb
<nav class="navbar navbar-light is-warning">
  <a class="navbar-brand" href="">
    <%= image_submit_tag('ACA.png')%>
    <div class= "text-right">
         <%= link_to "Cerrar sesión", destroy_user_session_path, 'data-turbo.method': :delete, class:"button is-warning is-outlined is-light"%>
    </div>
  </a>
</nav>
<div class="text-center">
<section class="hero is-warning is-fullheight">
  <div class="hero-body">
    <div class="container">
      <div class="columns is-centered">
        <div class="column is-5-tablet is-4-desktop is-4-widescreen box">
<h2 class="is-size-3">Actualizar licencia de conducir</h2><br>
 <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
   <%= render "users/shared/error_messages", resource: resource %>


   <div class="field has-text-weight-bold">
     <%= f.label :license,"Foto de licencia de conducir" %><br>
     <%= f.file_field :license %>
       <%= link_to "Ver", rails_blob_path(current_user.license.blob, disposition: 'preview') %>
   </div> 
    
   <div class="field has-text-weight-bold has-text-centered">
    <%= f.label :vencimiento_licencia,"Fecha de vencimiento Licencia" %><br>
    <%= f.date_field :vencimiento_licencia %><br><br>
   </div>
   
   <%= f.hidden_field :licencia_rechazada, value: false %>

   <div class="field has-text-weight-bold">
     <%= f.label :current_password, "Contraseña actual"%> <i>(para confirmar sus cambios)</i><br />
     <%= f.password_field :current_password, autocomplete: "current-password" %>
   </div>

   <div class="actions">
     <%= f.submit "Editar",class:"button is-warning is-outlined is-light",data: { turbo_confirm:'Estas seguro de que desea guardar cambios?' }%>
   </div>
 <% end %>

 <br>

 <%= link_to "Cancelar", :back %>
</div>
</div>
</div>
</div>
</section>
</div>

app/views/users/elegirSaldo.html.erb
<nav class="navbar navbar-light is-warning">
  <a class="navbar-brand" href="">
    <%= image_submit_tag('ACA.png')%>
    <div class= "text-right">
         <%= link_to "Cerrar sesión", destroy_user_session_path, 'data-turbo.method': :delete, class:"button is-warning is-outlined is-light"%>
    </div>
  </a>
</nav>
<br>
<br>
<div class = "text-center">
  <h2> Cada hora cuesta: $500 </h2>
</div>
<br>
<%= form_with model:(@us) do |user| %>
  <div class = "has-text-weight-bold text-center">
        <%= user.label :horas, "Elegir cantidad de horas"%>
        <%= user.number_field :horas,:min => 1, :max => 24 %>
  </div>
<br>
  <div class = "text-center">
       <%= user.submit "Cargar", class: "button is-warning is-outlined is-light" ,data: { turbo_confirm:'Estas seguro de que desea guardar los cambios?' }%>
  </div>
  <div class="volver">
      <%= link_to "Volver", user_usuario_path ,class: "button is-warning is-outlined is-light"%>
  </div>
<%end%>

app/views/users/home.html.erb
<nav class="level">
    <div class="level-left">
         <%= image_submit_tag('alqui.png')%>
    </div>

     <div class="level-right">
         <section class="hero is-warning is-fullheight is-large">
           <div class="hero-body hero-head hero-foot">
              <p class="title">
                  <%= link_to "Registrarse", new_user_registration_path,class:"button is-warning is-outlined is-light button is-large"%>
                  <%= link_to "Iniciar sesion", new_user_session_path, class:"button is-warning is-outlined is-light button is-large"%><br>
              </p>
           </div>
         </section>
     </div>
</nav>

app/views/users/listaLicencias.html.erb
<nav class="navbar navbar-light is-warning">
  <a class="navbar-brand" href="">
    <%= image_submit_tag('ACA.png')%>
    <div class= "text-right">
         <%= link_to "Cerrar sesión", destroy_user_session_path, 'data-turbo.method': :delete, class:"button is-warning is-outlined is-light" %>
    </div>
  </a>
</nav>

<% flash.each do |type, msg| %>
 <%if type=="danger" %>
   <div class="alert alert-danger">
     <%= msg %>
   </div>
  <%end%>
  <% if type=="notice" %>
    <div class="alert alert-success">
     <%= msg %>
    </div>
  <%end%>
<% end %>
<br>

<h1 class="text-center">Licencias Nuevas</h1>
<div class="table-wrapper">
    <table class="table table-bordered">
        <thead class="table-bordered">
            <tr class="table-warning">
                <th scope="col">Nombre</th>
                <th scope="col">Apellido</th>
                <th scope="col">DNI</th>
                <th scope="col">Vencimiento Licencia</th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>  
        <tbody>  
            <% @usuarios.each  do |u| %>
            <tr>
                <td><%= u.name%></td>
                <td><%= u.last_name %> </td>
                <td><%= u.dni_nro%></td>
                <td><%= u.vencimiento_licencia%></td>
                <td><%= link_to "Ver", rails_blob_path(u.license.blob, disposition: 'preview'), class:"button is-warning is-outlined is-light" %></td>
                <td>
                    <%= link_to 'Validar licencia', url_for(action: :validarLic, id: u.id), data: {turbo_method: :validarLic, turbo_confirm: 'Esta seguro que desea validar la licencia?'}, class: "button is-warning is-outlined is-light"%>
                </td>
                <td>
                    <%= link_to 'Rechazar licencia', url_for(action: :rechazarLic, id: u.id), data: {turbo_method: :rechazarLic, turbo_confirm: 'Esta seguro que desea rechazar la licencia?'}, class: "button is-warning is-outlined is-light"%>
                </td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>
    <div class = "text-center">
              <%= link_to "Volver",  user_supervisor_path, class: "button is-warning is-outlined is-light" %>
          </div>

app/views/users/userAdmin.html.erb
<nav class="navbar navbar-light is-warning">
  <a class="navbar-brand" href="">
    <%= image_submit_tag('ACA.png')%>
    <div class= "text-right">
         <%= link_to "Cerrar sesión", destroy_user_session_path, 'data-turbo.method': :delete, class:"button is-warning is-outlined is-light" %>
    </div>
  </a>
</nav>
<% flash.each do |type, msg| %>
  <% if type=="danger" %>
    <div class="alert alert-danger">
       <%= msg %>
    </div>
  <%end%>
  <% if type=="notice" %>
    <div class="alert alert-success">
     <%= msg %>
    </div>
  <%end%>
<% end %>
<br>


<button class="button is-warning is-outlined is-light isDisabled"><%= I18n.l(Date.today, format: '%d-%m-%Y') %> Hora: <%= Time.now.strftime("%H:%M") %></button>


<h3 class = "text-center"> Bienvenido administrador <%= @admin.name%> <%=@admin.last_name %></h3>

<br>
<div class= "text-center">
 <%= link_to "Listado de autos", cars_path, class:"button is-warning is-outlined is-light"%>
 <%= link_to "Lista Supervisores", user_admin_lista_path,class:"button is-warning is-outlined is-light" %>
 <%= link_to "Lista Administradores", user_admin_listaAdmin_path, class:"button is-warning is-outlined is-light" %>
 
</div>

app/views/users/userAdmin_editEmployees.html.erb
<nav class="navbar navbar-light is-warning">
  <a class="navbar-brand" href="">
    <%= image_submit_tag('ACA.png')%>
    <div class= "text-right">
         <%= link_to "Cerrar sesión", destroy_user_session_path, 'data-turbo.method': :delete, class:"button is-warning is-outlined is-light"%>
    </div>
  </a>
</nav>
<section class="hero is-warning is-fullheight"> 
<div class="hero-body text-center ">
        <div class="container ">
        <h2 class = "text-center">Editar Supervisor</h2><br>
            <div class="columns is-centered">
                <div class="column is-5-tablet is-4-desktop is-4-widescreen box">
                   

                    <%= form_for @supervisor do |s| %>
                              <% flash.each do |type, msg| %>
                                     <%= msg %>
                              <% end %>
                        <div class="field has-text-weight-bold has-text-centered">
                            <%= s.label :name,"Nombre" %><br>
                            <%= s.text_field :name %>
                        </div>

                        <div class="field has-text-weight-bold has-text-centered">
                            <%= s.label :last_name,"Apellido" %><br>
                            <%= s.text_field :last_name %>
                        </div>

                        <div class="field has-text-weight-bold has-text-centered">
                          <%= s.label :dni_nro,"DNI" %><br>
                          <%= s.text_field :dni_nro %>
                        </div>

                        <div class="field has-text-weight-bold has-text-centered actions">
                            <%= s.submit "Confirmar",class: "button is-warning is-outlined is-light",data: { turbo_confirm:'Estas seguro de que desea guardar cambios?' } %>
                        </div>

                    <% end %><br>
                    <div class="text-center">
                      <%= link_to "Volver", user_admin_lista_path,class: "button is-warning is-outlined is-light" %> 
                    </div>
                </div>
            </div>
        </div>
    </div>
</section> 

app/views/users/userAdmin_listAdmin.html.erb
<nav class="navbar navbar-light is-warning">
  <a class="navbar-brand" href="">
    <%= image_submit_tag('ACA.png')%>
    <div class= "text-right">
         <%= link_to "Cerrar sesión", destroy_user_session_path, 'data-turbo.method': :delete, class:"button is-warning is-outlined is-light"%>
    </div>
  </a>
</nav>
<% flash.each do |type, msg| %>
  <% if type=="danger" %>
    <div class="alert alert-danger">
       <%= msg %>
    </div>
  <%end%>
  <% if type=="notice" %>
    <div class="alert alert-success">
     <%= msg %>
    </div>
  <%end%>
<% end %>
<br>
<%= link_to "Agregar Administrador",  new_user_temp_admin_path,class:"button is-warning is-outlined is-light" %>
<div class= "text-center">
<h1>Administradores en el sistema</h1>
</div>
<div class="table-wrapper">
    <table class="table table-bordered">
     <thead class="table-bordered">
        <tr class="table-warning">
                <th scope="col">Nombre</th>
                <th scope="col">Apellido</th>
                <th scope="col">DNI</th>
        </tr>
     </thead>
       <tbody>
        <% @admin.each  do |a| %>
         <tr>
            <td><%= a.name%></td>
            <td><%= a.last_name %> </td>
            <td><%= a.dni_nro%></td>
         </tr>
        <% end %>
       </tbody>
   </table>
   </div>
    <br>
<div class="field has-text-weight-bold actions text-center">
<%= link_to "Volver", user_admin_path ,class: "button is-warning is-outlined is-light"%>
</div>

app/views/users/userAdmin_listaSupervisor.html.erb
<nav class="navbar navbar-light is-warning">
  <a class="navbar-brand" href="">
    <%= image_submit_tag('ACA.png')%>
    <div class= "text-right">
         <%= link_to "Cerrar sesión", destroy_user_session_path, 'data-turbo.method': :delete, class:"button is-warning is-outlined is-light"%>
    </div>
  </a>
</nav>
<% flash.each do |type, msg| %>
  <% if type=="danger" %>
    <div class="alert alert-danger">
       <%= msg %>
    </div>
  <%end%>
  <% if type=="notice" %>
    <div class="alert alert-success">
     <%= msg %>
    </div>
  <%end%>
<% end %>
<br>
<%= link_to "Agregar Supervisor",  new_user_temp_sup_path,class:"button is-warning is-outlined is-light" %>
<% if @supervisores.where(role: "supervisor").count>0 %>
<div class= "text-center">
<h1>Supervisores contratados</h1>
</div>
<div class="table-wrapper">
    <table class="table table-bordered">
     <thead class="table-bordered">
        <tr class="table-warning">
                <th scope="col">Nombre</th>
                <th scope="col">Apellido</th>
                <th scope="col">DNI</th>
                <th scope="col">Reclamo activo</th>
                <th scope="col"></th>
                <th scope="col"></th>
        </tr>
     </thead>
       <tbody>
        <% @supervisores.each  do |s| %>
         <tr>
            <td><%= s.name%></td>
            <td><%= s.last_name %> </td>
            <td><%= s.dni_nro%></td>
            <td><%= if s.reclamo
                      "Si"
                    else
                      "No"
                    end
            %></td>
            <td>
            <%= link_to 'Eliminar', url_for(action: :deleteSup, id: s.id), data: {turbo_method: :deleteSup, turbo_confirm: 'Esta seguro que desea eliminar el supervisor?'}, class: "button is-warning is-outlined is-light"%>
            </td>
            <td><%= link_to "Editar",  user_admin_editEmployees_path(s),class: "button is-warning is-outlined is-light", method: :userAdmin_editEmployees %></td>
         </tr>
        <% end %>
       </tbody>
   </table>
   </div>
<% else %>
<div class= "text-center">
<h1>No hay supervisores registrados</h1>
</div>
<% end %>
    <br>
<div class="field has-text-weight-bold actions text-center">
<%= link_to "Volver", user_admin_path ,class: "button is-warning is-outlined is-light"%>
</div>


   

app/views/users/userSupervisor.html.erb
<nav class="navbar navbar-light is-warning">
  <a class="navbar-brand" href="">
    <%= image_submit_tag('ACA.png')%>
    <div class= "text-right">
         <%= link_to "Cerrar sesión", destroy_user_session_path, 'data-turbo.method': :delete, class:"button is-warning is-outlined is-light" %>
    </div>
  </a>
</nav>
<% flash.each do |type, msg| %>
  <% if type=="danger" %>
    <div class="alert alert-danger">
       <%= msg %>
    </div>
  <%end%>
  <% if type=="notice" %>
    <div class="alert alert-success">
     <%= msg %>
    </div>
  <%end%>
<% end %>
<br>



<button class="button is-warning is-outlined is-light isDisabled"><%= I18n.l(Date.today, format: '%d-%m-%Y') %> Hora: <%= Time.now.strftime("%H:%M") %></button>

<h3 class = "text-center"> Bienvenido supervisor <%= @supervisor.name%> <%=@supervisor.last_name %></h3>

<br>
<div class= "text-center">
 <%= link_to "Listado de autos",  cars_path ,class: "button is-warning is-outlined is-light"%>
 <%= link_to "Nuevas licencias", listar_licencias_path, class: "button is-warning is-outlined is-light" %>
</div>

app/views/users/userUsuario.html.erb
<nav class="navbar navbar-light is-warning">
  <a class="navbar-brand" href="">
    <%= image_submit_tag('ACA.png')%>
    <div class= "text-right">
         <%= link_to "Cerrar sesión", destroy_user_session_path, 'data-turbo.method': :delete, class:"button is-warning is-outlined is-light"%>
    </div>
  </a>
</nav>
<% flash.each do |type, msg| %>
  <% if type=="danger" %>
    <div class="alert alert-danger">
       <%= msg %>
    </div>
  <%end%>
  <% if type=="warning" %>
  <div class="alert alert-warning">
     <%= msg %>
  </div>
  <%end%>
  <% if type=="notice" %>
    <div class="alert alert-success">
     <%= msg %>
    </div>
  <%end%>
<% end %>
<br>
 
<button class="button is-warning is-outlined is-light isDisabled"><%= I18n.l(Date.today, format: '%d-%m-%Y') %> Hora: <%= Time.now.strftime("%H:%M") %></button>



<h3 class="text-center"> Bienvenido usuario <%= @usuario.name%> <%=@usuario.last_name %></h3>

<br>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog ">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Saldo actual: </h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">X</button>
      </div>
      <div class="modal-body text-center">
        <h4>$<%= @usuario.saldo %></h4>
      </div>
    </div>
  </div>
</div>


<br>
<div class= "text-center">
<button type="button" class="button is-warning is-outlined is-light" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Consultar saldo
</button>
  <%= link_to "Cargar saldo",elegir_saldo_path(@usuario), class:"button is-warning is-outlined is-light" %>
  <%= link_to "Actualizar licencia",  user_usuario_actualizarLicencia_path,class:"button is-warning is-outlined is-light" %>
</div>
<br><br>
<%if (@usuario.vencimiento_licencia.mday <(I18n.l(Date.today, format: '%d')).to_i)&&(@usuario.vencimiento_licencia.mon <=(I18n.l(Date.today, format: '%m')).to_i)&&(@usuario.vencimiento_licencia.year <=(I18n.l(Date.today, format: '%Y')).to_i)%>
     <% @usuario.hayLicencia=false %>
     <% @usuario.save%>
     <div class="alert alert-danger text-center" role="alert">
       <h6>Tu licencia esta vencida. Para alquilar un auto actualice su licencia </h6>
     </div>
<%end%>