config/routes.rb
Rails.application.routes.draw do
  resources :user_temp_admins
  get 'mercadopago/index'
  get 'mercadopago/show'
  get 'mercadopago/new'
  get 'user_temp_sups/index'
  get 'user_temp_sups/show'
  get 'user_temp_sups/new',as:"new_user_temp_sup"
  resources :user_temp_sups
  #Rutas del admin
  resources :cars
  get "cars/pausar/:id", to: "cars#changeEnable",as:"cars_lista_id"
  patch "cars/pausar/:id", to: "cars#changeEnable",as:"cars_pausar"
  get "cars/activar/:id", to: "cars#changeEnable",as:"cars_lista_activar_id"
  patch "cars/activar/:id", to: "cars#changeEnable",as:"cars_activar"
  get "cars/delete/:id", to: "cars#destroy"
  delete "cars/delete/:id", to: "cars#destroy", as:"cars_delete"
  get "cars/deleteCar/:id", to: "cars#deleteCar"
  delete "cars/deleteCar/:id", to: "cars#deleteCar", as:"cars_deletecar"
  #Rutas del admin
  get "users/admin", to: "users#userAdmin", as: "user_admin"
  get "users/admin/newSup", to: "users#newSup", as: "user_admin_agregarSupervisor"
  post "users/admin", to: "users#create"
  get "users/admin/listaSupervisor", to: "users#userAdmin_listaSupervisor", as: "user_admin_lista"
  get "users/admin/listaAdministradores", to: "users#userAdmin_listAdmin", as: "user_admin_listaAdmin"
  get '/user/:id', to: 'users#show', as: 'user'
  get 'users/admin/listaSupervisor/:id/edit_employees', to: 'users#userAdmin_editEmployees', as: 'user_admin_editEmployees'
  patch 'user/:id', to: 'users#update_Employees'
  get "users/admin/listaSupervisor/:id", to: "users#deleteSup", as: "user_admin_lista_id"
  delete 'users/admin/listaSupervisor/:id', to: 'users#deleteSup', as: 'superv_delete'
  #Rutas del usuario
  get "users/usuario", to: "users#userUsuario", as: "user_usuario"
  get "users/usuario/actualizarLicencia", to: "users#actualizarLicencia", as: "user_usuario_actualizarLicencia"

  
  #Rutas del supervisor
  get "users/supervisor", to: "users#userSupervisor", as: "user_supervisor"
  resources :users, only: [:index]
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "users#home"


  get 'users/supervisor/listaLicencias', to: 'users#listaLicencias', as: 'listar_licencias'

  get 'users/supervisor/confirm/:id', to: 'users#validarLic', as: 'validar_licencia_id'
  patch 'users/supervisor/confirm/:id', to: 'users#validarLic', as: 'validar_licencia'

  get 'users/supervisor/confirm/rechazar/:id', to: 'users#rechazarLic', as: 'rechazar_licencia_id'
  patch 'users/supervisor/confirm/rechazar/:id', to: 'users#rechazarLic', as: 'rechazar_licencia'


  get 'users/usuario/:id/elegirsaldo', to: 'users#elegirSaldo', as: 'elegir_saldo'


  get 'mercadopago/success', to: 'mercadopago#success'
  get 'mercadopago/pending', to: 'mercadopago#pending'
  get 'mercadopago/failure', to: 'mercadopago#failure'

end

app/models/car.rb
class Car < ApplicationRecord
    validates :patent, uniqueness:  { message: 'ya existe en el sistema' }, presence: { message: 'en blanco' }
    validates :brand, presence: { message: 'en blanco' }
    validates :model_car, presence: { message: 'en blanco' }
    validates :seats, presence: { message: 'en blanco' }
    validates :transmision, presence: { message: 'en blanco' }
    validates :fuel, presence: { message: 'en blanco' }
    validates :color, presence: { message: 'en blanco' }
    validates :car_number, uniqueness:  { message: 'ya existe en el sistema' }, presence: { message: 'en blanco' } 
    validates :year_model, presence: { message: 'en blanco' }

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]
  #before_action :is_admin
  # GET /cars or /cars.json
  add_flash_types :danger,:warning,:notice
  
  def index
    @cars = Car.all
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)
    if current_user
      respond_to do |format|
        if @car.save
            format.html { redirect_to cars_path, notice: "El auto fue agregado exitosamente." }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @car.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
      respond_to do |format|
        if @car.update(car_params)
            format.html { redirect_to cars_path, notice: "El auto fue editado exitosamente." }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @car.errors, status: :unprocessable_entity }
        end
      end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    if @car.is_available
      @car.destroy
      respond_to do |format|
        format.html { redirect_to cars_path, notice: "Auto eliminado correctamente." }
        format.json { head :no_content }
      end
    else
      redirect_to cars_path, danger: "No se puede eliminar un auto si se encuentra en uso"
    end
  end
  
  def deleteCar
    @car= Car.find(params[:id])
    if @car.is_available ==true
      @car.destroy
      respond_to do |format|
        format.html { redirect_to cars_path, notice: "Auto eliminado correctamente." }
        format.json { head :no_content }
      end
    else
      redirect_to cars_path, danger: "No se puede eliminar un auto si se encuentra en uso"
    end
  end
  def changeEnable
    @car=Car.find(params[:id])
    if @car.is_available && @car.is_enable
      @car.is_enable=false
      if @car.save
        redirect_to cars_path, notice: "Se ha pausado el auto con exito"
      else
        redirect_to cars_path, danger: "No se puede pausar un auto si se encuentra en uso"
      end
    else 
        @car.is_enable=true
        if @car.save
          redirect_to cars_path, notice: "Se ha activado el auto con exito"
        else
          redirect_to cars_path, danger: "No se puede activar auto"
        end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
     @car = Car.find(params[:id])
    end

    def is_admin
       if !(current_user && current_user.role=="administrador")
        redirect_to root_path 
       end
    end
    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:patent, :brand, :model_car, :seats, :transmision, :fuel, :is_available, :is_enable, :color, :car_number, :year_model)
    end
  
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
  <p>
    <strong>Patente:</strong>
    <%= car.patent %>
  </p>

  <p>
    <strong>Brand:</strong>
    <%= car.brand %>
  </p>

  <p>
    <strong>Model car:</strong>
    <%= car.model_car %>
  </p>

  <p>
    <strong>Seats:</strong>
    <%= car.seats %>
  </p>

  <p>
    <strong>Transmision:</strong>
    <%= car.transmision %>
  </p>

  <p>
    <strong>Fuel:</strong>
    <%= car.fuel %>
  </p>

  <p>
    <strong>Is available:</strong>
    <%= car.is_available %>
  </p>

  <p>
    <strong>Is enable:</strong>
    <%= car.is_enable %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= car.color %>
  </p>

  <p>
    <strong>Car number:</strong>
    <%= car.car_number %>
  </p>

  <p>
    <strong>Year model:</strong>
    <%= car.year_model %>
  </p>


</div>

app/views/cars/_form.html.erb
<div class = "text-center">
    <section class="hero is-warning ">
        <div class="hero-body">
            <div class="container">
                <div class="columns is-centered">
                    <div class="column is-5-tablet is-4-desktop is-4-widescreen box">

                      <%= form_with(model: car) do |form| %>
                        <% if car.errors.any? %>
                          <div style="color: red">
                            <h2><%= pluralize(car.errors.count, "error") %></h2>

                            <ul>
                              <% car.errors.each do |error| %>
                                <li><%= error.full_message %></li>
                              <% end %>
                            </ul>
                          </div>
                        <% end %>

                        <div class = "has-text-weight-bold">
                          <%= form.label :patent,"Patente", style: "display: block" %>
                          <%= form.text_field :patent %>
                        </div>

                        <div class = "has-text-weight-bold">
                          <%= form.label :brand,"Marca", style: "display: block" %>
                          <%= form.text_field :brand %>
                        </div>

                        <div class = "has-text-weight-bold">
                          <%= form.label :model_car,"Modelo", style: "display: block" %>
                          <%= form.text_field :model_car %>
                        </div>


                        <div class = "has-text-weight-bold">
                          <%= form.label :seats, "Asientos", style: "display: block" %>
                          <%= form.number_field :seats, :min => 2, :max => 12 %>
                        </div>

                        <div class = "has-text-weight-bold">
                          <%= form.label :transmision, "Transmisión", style: "display: block" %>
                          <%= form.text_field :transmision %>
                        </div>

                        <div class = "has-text-weight-bold">
                          <%= form.label :fuel, "Tipo de combustible", style: "display: block" %>
                          <%= form.text_field :fuel %>
                        </div>

                        <div class = "has-text-weight-bold">
                          <%= form.hidden_field :is_available, value: true %>
                        </div>

                        <div class = "has-text-weight-bold">
                          <label> Esta activado <%= form.check_box :is_enable %> </label>
                        </div>

                        <div class = "has-text-weight-bold">
                          <%= form.label :color, "Color", style: "display: block" %>
                          <%= form.text_field :color %>
                        </div>

                        <div class = "has-text-weight-bold">
                          <%= form.label :car_number, "Numero de auto (VIN)", style: "display: block" %>
                          <%= form.number_field :car_number, :min => 1 %>
                        </div>

                        <div class = "has-text-weight-bold">
                          <%= form.label :year_model, "Año del modelo", style: "display: block" %>
                          <%= form.number_field :year_model, :min => 1 %>
                        </div>

                        <br>
                        <div>
                          <%= form.submit "Confirmar", class: "button is-warning is-outlined is-light" ,data: { turbo_confirm:'Estas seguro de que desea guardar los cambios?' }%>
                        </div>
  
                      <% end %>
                    </div>
                </div>
            </div>
        </div>
    </section> 
</div>

app/views/cars/edit.html.erb
<nav class="navbar navbar-light is-warning">
  <a class="navbar-brand" href="">
    <%= image_submit_tag('ACA.png')%>
    <div class= "text-right">
         <%= link_to "Cerrar sesión", destroy_user_session_path, 'data-turbo.method': :delete, class:"button is-warning is-outlined is-light"%>
    </div>
  </a>
</nav>
<section class="hero is-warning ">
    <div class="hero-body">
        <h3 class = "text-center">Editar auto</h3><br>


        <%= render "form", car: @car %>


        <div class = "text-center">
            <%= link_to "Volver",  cars_path, class: "button is-warning is-outlined is-light" %>
        </div>

    </div>
</section>

app/views/cars/index.html.erb
<nav class="navbar navbar-light is-warning">
  <a class="navbar-brand" href="">
    <%= image_submit_tag('ACA.png')%>
    <div class= "text-right">
         <%= link_to "Cerrar sesión", destroy_user_session_path, 'data-turbo.method': :delete, class:"button is-warning is-outlined is-light"%>
    </div>
  </a>
</nav>
<% flash.each do |type, msg| %>
 <%if type=="danger" %>
   <div class="alert alert-danger">
     <%= msg %>
   </div>
  <%end%>
  <% if type=="notice" %>
    <div class="alert alert-success">
     <%= msg %>
    </div>
  <%end%>
<% end %>

<br>
<%= link_to "Agregar Auto", new_car_path, class:"button is-warning is-outlined is-light" %>
<% if @cars.count>0 %>
<h1 class="text-center">Lista de autos</h1>
<div class="table-wrapper">
<table class="table table-bordered">
  <thead class="table-bordered">
    <tr class="table-warning">
      <th scope="col">Número de auto</th>
      <th scope="col">Patente</th>
      <th scope="col">Marca</th>
      <th scope="col">Modelo</th>
      <th scope="col">Cantidad de asientos</th>
      <th scope="col">Caja de transmision</th>
      <th scope="col">Combustible</th>
      <th scope="col">Disponible</th>
      <th scope="col">Activado</th>
      <th scope="col">Color</th>
      <th scope="col">Año del modelo</th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @cars.each do |c| %>
      <tr>
        <td><%=c.car_number%></td>
        <td><%=c.patent%></td>
        <td><%=c.brand%></td>
        <td><%=c.model_car%></td>
        <td><%=c.seats%></td>
        <td><%=c.transmision%></td>
        <td><%=c.fuel%></td>
        <td><%=if c.is_available 
                  "Si"
               else
                  "No"
               end
         %></td>
        <td><%=if c.is_enable
                "Si"
                else 
                  "No"
                end
         %></td>
        <td><%=c.color%></td>
        <td><%=c.year_model%></td>
        <td> <% if c.is_available%>
                <%=link_to "Editar", edit_car_path(c), class:"button is-warning is-outlined is-light" %>
             <% else%>
               <%=link_to "Editar", edit_car_path(c), class:"button is-warning is-outlined is-light isDisabled" %>
             <% end%>
        </td>
        <% if c.is_enable%>
        <td>
              <%= link_to 'Pausar auto', url_for(action: :changeEnable, id: c.id), data: {turbo_method: :changeEnable, turbo_confirm: 'Esta seguro que desea pausar el auto?'}, class: "button is-warning is-outlined is-light"%>
        </td>
        <% else %>
        <td>
              <%= link_to 'Activar auto', url_for(action: :changeEnable, id: c.id), data: {turbo_method: :cahngeEnable, turbo_confirm: 'Esta seguro que desea activar el auto?'}, class: "button is-warning is-outlined is-light"%>  
        </td>
        <% end %>
        <td><!--<%=link_to "Eliminar", cars_delete_path(c.id),  class:"button is-warning is-outlined is-light",data: { turbo_confirm:'Estas seguro de que desea eliminar el auto?' } %>-->
            <%= link_to 'Eliminar auto', url_for(action: :deleteCar, id: c.id), data: {turbo_method: :deleteCar, turbo_confirm: 'Esta seguro que desea eliminar el auto?'}, class: "button is-warning is-outlined is-light"%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<% else %>
    <div class= "text-center">
        <h1>No hay autos registrados</h1>
    </div>
<% end %>
    <br>
<% if current_user %>
      <% if current_user.role == "supervisor" %>
          <div class = "text-center">
              <%= link_to "Volver",  user_supervisor_path, class: "button is-warning is-outlined is-light" %>
          </div>
      <% end %>
      <%if current_user.role == "administrador" %>
          <div class = "text-center">
              <%= link_to "Volver",  user_admin_path, class: "button is-warning is-outlined is-light" %>
          </div>
      <% end %>
<% end %>

app/views/cars/new.html.erb
<nav class="navbar navbar-light is-warning">
  <a class="navbar-brand" href="">
    <%= image_submit_tag('ACA.png')%>
    <div class= "text-right">
         <%= link_to "Cerrar sesión", destroy_user_session_path, 'data-turbo.method': :delete, class:"button is-warning is-outlined is-light"%>
    </div>
  </a>
</nav>
<section class="hero is-warning ">
    <div class="hero-body">
        <h3 class = "text-center">Agregar auto</h3><br>
 

        <%= render "form", car: @car %>

        
        <div class = "text-center">
            <%= link_to "Volver",  cars_path, class: "button is-warning is-outlined is-light" %>
        </div>
         
        <br>
    </div>
    <br>
    <br>
</section>

app/views/cars/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @car %>

<div>

  <%= button_to "Eliminar", @car, method: :delete %>
</div>